### ISSUE TITLE
Error migrating to 1.24.1 server

### ISSUE THREAD

**Issue by dimm0** [piraeusdatastore/piraeus-operator#521]
Clusterrole linstor-controller needs the `deletecollection` permission

```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.linbit.linstor.core.LinstorConfigTool$CmdRunMigration@5ce81285): com.linbit.SystemServiceStartException: Database initialization error
	at picocli.CommandLine.executeUserObject(CommandLine.java:2050)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.linbit.linstor.core.LinstorConfigTool.main(LinstorConfigTool.java:376)
Caused by: com.linbit.SystemServiceStartException: Database initialization error
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrdInitializer.initialize(DbK8sCrdInitializer.java:59)
	at com.linbit.linstor.core.LinstorConfigTool$CmdRunMigration.call(LinstorConfigTool.java:336)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	... 8 more
Caused by: com.linbit.linstor.LinStorDBRuntimeException: Exception occurred during migration
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:191)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:124)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrdInitializer.initialize(DbK8sCrdInitializer.java:54)
	... 10 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://10.96.0.1:443/apis/internal.linstor.linbit.com/v1/rollback. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. rollback.internal.linstor.linbit.com is forbidden: User "system:serviceaccount:piraeus-datastore:linstor-controller" cannot deletecollection resource "rollback" in API group "internal.linstor.linbit.com" at the cluster scope.
	at io.fabric8.kubernetes.client.KubernetesClientException.copyAsCause(KubernetesClientException.java:238)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:518)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleDelete(OperationSupport.java:320)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.deleteAll(BaseOperation.java:504)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.delete(BaseOperation.java:469)
	at com.linbit.linstor.transaction.ControllerK8sCrdRollbackMgr.cleanup(ControllerK8sCrdRollbackMgr.java:115)
	at com.linbit.linstor.transaction.ControllerK8sCrdTransactionMgr.commit(ControllerK8sCrdTransactionMgr.java:182)
	at com.linbit.linstor.dbcp.migration.k8s.crd.BaseK8sCrdMigration.migrate(BaseK8sCrdMigration.java:252)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:179)
	... 12 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: DELETE at: https://10.96.0.1:443/apis/internal.linstor.linbit.com/v1/rollback. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. rollback.internal.linstor.linbit.com is forbidden: User "system:serviceaccount:piraeus-datastore:linstor-controller" cannot deletecollection resource "rollback" in API group "internal.linstor.linbit.com" at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:671)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:651)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.assertResponseCode(OperationSupport.java:597)
	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.lambda$handleResponse$0(OperationSupport.java:560)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.http.StandardHttpClient.lambda$completeOrCancel$10(StandardHttpClient.java:140)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.http.ByteArrayBodyHandler.onBodyDone(ByteArrayBodyHandler.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.fabric8.kubernetes.client.okhttp.OkHttpClientImpl$OkHttpAsyncBody.doConsume(OkHttpClientImpl.java:137)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by WanzenBug** [comment]
This is already fixed in the `v2` branch: https://github.com/piraeusdatastore/piraeus-operator/commit/d21d5f06df739ac8bb232f0f6690b1a9c4080e79

But there is no new release, the existing 2.1.1 release is only tested for LINSTOR 1.23.0
