### ISSUE TITLE
Cannot perform Migration 5 while a rollback has to be done

### ISSUE THREAD

**Issue by Nosmoht** [piraeusdatastore/piraeus-operator#534]
Hi All,

i tried to upgrade from a v2 ref to v2.2.0 (tried also v2.1.1 first) but always get the same error message. Anybody could support me fixing the issue?

I'm running Kubernetes v1.28.2 on top of Talos. Please find bellow the error log from `run-migration` container of `piraeus-server:v1.24.2`.

```sh
TRACE:   Found database version 4
DEBUG:   Migration DB: 4 -> 5: Rename netcom to NetCom namespace
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.linbit.linstor.core.LinstorConfigTool$CmdRunMigration@4fe3c938): com.linbit.SystemServiceStartException: Database initialization error
	at picocli.CommandLine.executeUserObject(CommandLine.java:2050)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.linbit.linstor.core.LinstorConfigTool.main(LinstorConfigTool.java:376)
Caused by: com.linbit.SystemServiceStartException: Database initialization error
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrdInitializer.initialize(DbK8sCrdInitializer.java:59)
	at com.linbit.linstor.core.LinstorConfigTool$CmdRunMigration.call(LinstorConfigTool.java:336)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	... 8 more
Caused by: com.linbit.linstor.LinStorDBRuntimeException: Exception occurred during migration
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:191)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:124)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrdInitializer.initialize(DbK8sCrdInitializer.java:54)
	... 10 more
Caused by: com.linbit.linstor.dbdrivers.DatabaseException: Cannot perform Migration 5 while a rollback has to be done
	at com.linbit.linstor.dbcp.migration.k8s.crd.BaseK8sCrdMigration.migrate(BaseK8sCrdMigration.java:241)
	at com.linbit.linstor.dbcp.k8s.crd.DbK8sCrd.migrate(DbK8sCrd.java:179)
	... 12 more
time="2023-10-05T13:30:50Z" level=fatal msg="failed to run" err="exit status 1"
```

As the error message says `while a rollback has to be done` i would like to know how to do the rollback.

Thanks in advance

**Comment by WanzenBug** [comment]
Hmm, looks like a linstor issue. Please open an issue over at https://github.com/LINBIT/linstor-server/

**Comment by Nosmoht** [comment]
Hi all,

just for information if others face the same issue: i was able to fix it by deleting all CRD's and restarting the linstor controller so it installed them from scratch.

```
$ for i in $(kubectl get crd | grep linstor | awk '{print $1}'); do kubectl delete crd $i; done

customresourcedefinition.apiextensions.k8s.io "files.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "keyvaluestore.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerbcachevolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layercachevolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerdrbdresourcedefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerdrbdresources.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerdrbdvolumedefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerdrbdvolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerluksvolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layeropenflexresourcedefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layeropenflexvolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerresourceids.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerstoragevolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "layerwritecachevolumes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "linstorremotes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "linstorsatellites.piraeus.io" deleted
customresourcedefinition.apiextensions.k8s.io "linstorversion.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "nodeconnections.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "nodenetinterfaces.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "nodes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "nodestorpool.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "propscontainers.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "resourceconnections.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "resourcedefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "resourcegroups.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "resources.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "rollback.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "s3remotes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "satellitescapacity.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secaccesstypes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secaclmap.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secconfiguration.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secdfltroles.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secidentities.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secidrolemap.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secobjectprotection.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "secroles.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "sectyperules.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "sectypes.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "spacehistory.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "storpooldefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "trackingdate.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "volumeconnections.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "volumedefinitions.internal.linstor.linbit.com" deleted
customresourcedefinition.apiextensions.k8s.io "volumegroups.internal.linstor.linbit.com" deleted
```
